= Elasticsearch and Evergreen =

== Goals ==

Fast bib record searching without requiring significant changes to
the Evergreen code and without requiring a brand new indexing configuration.

Initially support integration with the Angular staff catalog, covering 
most search features commonly used by staff.

Allow for expanding use to other interfaces (e.g. TPAC) and extending
functionatlity.

== Installation ==

1. Install and run a 6.8.* version of ES:
   https://www.elastic.co/downloads/past-releases/elasticsearch-6-8-3
2. Check out this Evergreen branch.
3. Apply SQL Open-ILS/src/sql/Pg/upgrade/XXXX.schema.elastic-search.sql
4. cd Open-ILS/src/eg2/ && npm install # new dependency
5. Build and Install branch

== Configuration ==

See database tables in the 'elastic' schema.  No admin UI exists.  If a 
single elasticsearch node is running on the same server as EG, no 
configuration changes are needed.

== Indexing Bib Records ==

See Open-ILS/src/support-scripts/elastic-index.pl

Examples:

[source,sh]
------------------------------------------------------------------------------
./elastic-index.pl --create-index --populate
./elastic-index.pl --delete-index --create-index --populate
./elastic-index.pl --populate --modified-since 2019-09-17T14:45:00
------------------------------------------------------------------------------

== Bib Search Index ==

A single 'bib-search' index is defined by default.  The structure of the index
is derived from the local Evergreen index definitions.  No additional index
definitions or modifications are required to get started.

=== General Stucture ===

The bib-search index contains 3 general categories of data for each 
bib record: 

1. Bib record search/filter data pulled from metabib fields and record 
   attribute definitions
2. MARC record data
3. Holdings summaries for filtering by library, availability, etc.

=== Search Fields ===

Search fields are grouped by search class (title, author, etc.).  Searches
can be performed against a specific field or across the class.

Search field values are extracted from metabib.*_field_entry tables
and reindexed in Elasticsearch using a combination of text and keyword
analyzers: default text, language-specific text, asciifolding text
(e.g. Grandpré => Grandpre) and lowercase keyword (for exact matches).

==== Caveats ====

* Author fields are not presently indexed with language-specific analyzers, 
  since the values are generally proper names.
* Keyword fields are not processed via lowercase keyword index, since exact
  matches on keyword indexes makes little sense.
* ISBN and ISSN values are specially handled for data cleanup and supporting
  isbn 10 / 13 searches.

=== Facet Fields ===

Field marked as facets get an extra '.facet' property which is a raw, 
unprocessed copy of the data used for aggregation.

=== Filter Fields ===

These concist of record attribute values and are indexed as simple
'keyword' entries, lowercased for ease of searching / filtering.

=== MARC Data ===

The full MARC record is included in the bib search index as a series
of nested objects.  This makes it possible to search MARC data in 
addition to (or instead of) search/filter fields, including filtering
on holdings.

=== Holdings ===

A set of holdings summaries are included with each bib record as nested 
objects.  The summaries track circ lib, shelf location, etc. so the caller
can determine org visibility and availability.

== API ==

New APIs were added:

open-ils.search.elastic.bib_search[.staff]

These allow the caller to compose Elasticsearch query structures which are
passed, with API-local additions, to the ES engine.  The response structure 
mimics the open-ils.search.biblio.multiclass.query class of APIs.

Additional options may be passed to the elastic API to include holdings-level
location and availability filtering.  (Note the client could add such filters, 
but baking it into the API saves the client a lot of work for a common work flow).

Facets are generated from ES and included in the API response.  No external 
faceting or facet caching is required.

== User Interface ==

The branch includes an Elastic service baked into the Angular staff catalog. 
It uses the elastic-builder module for creating the search structures.  

== Test Scripts ==

* Open-ILS/src/support-scripts/test-scripts/elastic-search.pl
** Allows the user to execute query_string-based searches.

* Open-ILS/src/support-scripts/test-scripts/elastic-search-samples.pl
** Runs a few canned searches as examples.

== Features Pending ==

Some existing Evergreen features are not supported by the ES API, though in
most if not all cases they can be added.

* Popularity ranking

